# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ImageProcessor_pb2 as ImageProcessor__pb2


class ImageProcessorStub(object):
    """Definition of the ImageProcessor service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processImage = channel.unary_unary(
                '/imageprocessing.ImageProcessor/processImage',
                request_serializer=ImageProcessor__pb2.ProcessImageRequest.SerializeToString,
                response_deserializer=ImageProcessor__pb2.ProcessImageResponse.FromString,
                )


class ImageProcessorServicer(object):
    """Definition of the ImageProcessor service
    """

    def processImage(self, request, context):
        """Processes an input image with a list of requested image processing operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processImage': grpc.unary_unary_rpc_method_handler(
                    servicer.processImage,
                    request_deserializer=ImageProcessor__pb2.ProcessImageRequest.FromString,
                    response_serializer=ImageProcessor__pb2.ProcessImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageprocessing.ImageProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageProcessor(object):
    """Definition of the ImageProcessor service
    """

    @staticmethod
    def processImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageprocessing.ImageProcessor/processImage',
            ImageProcessor__pb2.ProcessImageRequest.SerializeToString,
            ImageProcessor__pb2.ProcessImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
