# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageProcessor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ImageProcessor.proto\x12\x0fimageprocessing\"u\n\x13ProcessImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x11\n\timageType\x18\x02 \x01(\t\x12<\n\noperations\x18\x03 \x03(\x0b\x32(.imageprocessing.ImageProcessorOperation\"%\n\x14ProcessImageResponse\x12\r\n\x05image\x18\x01 \x03(\x0c\"?\n\nFlipParams\x12\x31\n\tdirection\x18\x01 \x01(\x0e\x32\x1e.imageprocessing.FlipDirection\"\x11\n\x0fGrayscaleParams\"\x1d\n\x0cRotateParams\x12\r\n\x05\x61ngle\x18\x01 \x01(\x05\"-\n\x0cResizeParams\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"0\n\x0fThumbnailParams\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\xba\x02\n\x17ImageProcessorOperation\x12\x15\n\roperationType\x18\x01 \x01(\t\x12+\n\x04\x66lip\x18\x02 \x01(\x0b\x32\x1b.imageprocessing.FlipParamsH\x00\x12\x35\n\tgrayscale\x18\x03 \x01(\x0b\x32 .imageprocessing.GrayscaleParamsH\x00\x12/\n\x06rotate\x18\x04 \x01(\x0b\x32\x1d.imageprocessing.RotateParamsH\x00\x12/\n\x06resize\x18\x05 \x01(\x0b\x32\x1d.imageprocessing.ResizeParamsH\x00\x12\x35\n\tthumbnail\x18\x06 \x01(\x0b\x32 .imageprocessing.ThumbnailParamsH\x00\x42\x0b\n\toperation*-\n\rFlipDirection\x12\x0e\n\nHORIZONTAL\x10\x00\x12\x0c\n\x08VERTICAL\x10\x01\x32o\n\x0eImageProcessor\x12]\n\x0cprocessImage\x12$.imageprocessing.ProcessImageRequest\x1a%.imageprocessing.ProcessImageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ImageProcessor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLIPDIRECTION._serialized_start=728
  _FLIPDIRECTION._serialized_end=773
  _PROCESSIMAGEREQUEST._serialized_start=41
  _PROCESSIMAGEREQUEST._serialized_end=158
  _PROCESSIMAGERESPONSE._serialized_start=160
  _PROCESSIMAGERESPONSE._serialized_end=197
  _FLIPPARAMS._serialized_start=199
  _FLIPPARAMS._serialized_end=262
  _GRAYSCALEPARAMS._serialized_start=264
  _GRAYSCALEPARAMS._serialized_end=281
  _ROTATEPARAMS._serialized_start=283
  _ROTATEPARAMS._serialized_end=312
  _RESIZEPARAMS._serialized_start=314
  _RESIZEPARAMS._serialized_end=359
  _THUMBNAILPARAMS._serialized_start=361
  _THUMBNAILPARAMS._serialized_end=409
  _IMAGEPROCESSOROPERATION._serialized_start=412
  _IMAGEPROCESSOROPERATION._serialized_end=726
  _IMAGEPROCESSOR._serialized_start=775
  _IMAGEPROCESSOR._serialized_end=886
# @@protoc_insertion_point(module_scope)
